-- drops all procedures
DROP PROCEDURE IF EXISTS insertRecipient;
DROP PROCEDURE IF EXISTS insertInd;
DROP PROCEDURE IF EXISTS insertOrg;
DROP PROCEDURE IF EXISTS insertAff;
DROP PROCEDURE IF EXISTS insertPrize;
DROP PROCEDURE IF EXISTS insertAffTo;
DROP PROCEDURE IF EXISTS insertAwardTo;
DROP PROCEDURE IF EXISTS DeleteRecipient;
DROP PROCEDURE IF EXISTS DeleteOrganisation;
DROP PROCEDURE IF EXISTS DeleteIndividual;
DROP PROCEDURE IF EXISTS DeleteAffiliate;
DROP PROCEDURE IF EXISTS DeletePrize;
DROP PROCEDURE IF EXISTS CountPhysicsAwards;

